### ISSUE TITLE
Bot not updating gsheet with match results

### ISSUE THREAD

**Issue by incnone** [incnone/condorbot#7]
I suspect the regex code in condormatch.CondorRacer.gsheet_regex is incorrect again somehow, and this is making the bot unable to correctly find the row on the gsheet corresponding to a match, and hence not updating correctly.

**Comment by alexismartin** [comment]
It was the bot_config.txt file that points to 'Test NDWC matchup chart' instead of 'NDWC matchup chart' that got reverted because of the pull. I fixed it on the server, you might want to change the file in the repo too.
